  version: 1.0.0
  description:
servers:
  - url: http://xxx
paths:
  /sam/predict:
    post:
      operationId: sam
      description: 进行sam分割
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SamRequestSchema'
      responses:
        '200':
          description: Successful SSE respponse
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/SamResponseSchema'
components:
  schemas:
    SamRequestSchema:
      type: object
      properties:
        fileUrl:
          type: string
          description: 文字路径地址。如果请求中有地址，只填写fileUrl参数，切勿填写历史记录中的生成结果
    SamResponseSchema:
      type: object
      properties:
        errCode:
          type: integer
          description: 插件响应的业务错误码
        errMsg:
          type: string
          description: 插件响应的业务错误信息
        status:
          type: string
          description: 当前请求的状态信息
        result:
          type: string
          description: 词云生成结果
        actionName:
          type: string
          description: 执行动作名称
        actionContent:
          type: string
          description: 执行动作内容